# Generated by Django 3.2.2 on 2021-05-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=14, unique=True)),
                ('data_nasc', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('mae', models.CharField(max_length=120)),
                ('pai', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=20)),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('tipo_sanguineo', models.CharField(max_length=4)),
            ],
        ),
    ]
